#!/bin/bash

# (c) 2012 Aurélien Gâteau <agateau@kde.org>
# MIT License
#
# Thin wrapper for make which:
# - logs output to /tmp/mymake.err, to be used with mymake.vim
# - shows notifications when done
if [ -z "$MAKEPRG" ] ; then
    MAKEPRG=make
fi

LOG_FILE=/tmp/mymake.err

build_dir=$(echo $PWD | sed "s,^$HOME,~,")

$MAKEPRG "$@" 2>&1 | tee $LOG_FILE
result=$PIPESTATUS
if [ $result -eq 0 ] ; then
    body="Build completed in $build_dir"
    warn_count=$(grep warning: $LOG_FILE | wc -l)
    if [ "$warn_count" = "0" ] ; then
        title="Build OK"
        icon="dialog-ok-apply" #green tick
    else
        if [ "$warn_count" = "1" ] ; then
            title="Build OK: 1 warning"
        else
            title="Build OK: $warn_count warnings"
        fi
        icon="dialog-warning"
    fi
else
    title="Build failed"
    body="Build failed in $build_dir"
    icon="dialog-error" #red square with white X
fi

which notify-send > /dev/null 2>&1 && notify-send --expire-time=2000 -i "$icon" -- "$title" "$body"

exit $result
