#!/bin/bash
# (c) 2012 Aurélien Gâteau <agateau@kde.org>
# MIT License
#
# Thin wrapper for make which:
# - logs output to /tmp/mymake.err, to be used with mymake.vim
# - shows notifications when done
# - automatically set -j if possible

set -euo pipefail
IFS=$'\n\t'

MAKEPRG=${MAKEPRG:-make}

LOG_FILE=/tmp/mymake.err

notify_result() {
    local icon=$1
    local title=$2
    local body=$3
    if ! which notify-send > /dev/null 2>&1 ; then
        return
    fi
    if [ -z "$DISPLAY" ]; then
        return
    fi
    notify-send --expire-time=2000 -i "$icon" -- "$title" "$body"
}

build_dir=$(echo $PWD | sed "s,^$HOME,~,")

extra_args=""
if which nproc > /dev/null 2>&1 ; then
    extra_args=-j$(nproc)
fi

$MAKEPRG $extra_args "$@" 2>&1 | tee $LOG_FILE
result=$PIPESTATUS
if [ $result -eq 0 ] ; then
    body="Build completed in $build_dir"
    warn_count=$(grep --count warning: $LOG_FILE || true)
    if [ "$warn_count" = "0" ] ; then
        title="Build OK"
        icon="dialog-ok-apply" #green tick
    else
        if [ "$warn_count" = "1" ] ; then
            title="Build OK: 1 warning"
        else
            title="Build OK: $warn_count warnings"
        fi
        icon="dialog-warning"
    fi
else
    title="Build failed"
    body="Build failed in $build_dir"
    icon="dialog-error" #red square with white X
fi

notify_result "$icon" "$title" "$body"

exit $result
