#!/bin/bash

# (c) 2012 Aurélien Gâteau <agateau@kde.org>
# MIT License
#
# Thin wrapper for make which:
# - logs output to /tmp/mymake.err, to be used with mymake.vim
# - shows notifications when done
if [ -z "$MAKEPRG" ] ; then
    MAKEPRG=make
fi

$MAKEPRG "$@" 2>&1 | tee /tmp/mymake.err
result=$PIPESTATUS
if [ $result -eq 0 ] ; then
    title="Build OK"
    body="Build completed in $PWD"
else
    title="Build failed"
    body="Build failed in $PWD"
fi

which notify-send 2>&1 > /dev/null && notify-send --expire-time=2000 -- "$title" "$body"

exit $result
